export const PLAYERS = [
  {
    id: "josh-allen",
    name: "Josh Allen",
    position: "QB",
    team: "BUF",
    byeWeek: 12,
    projStd: 24.4,
    projPpr: 24.4,
    ros: 23.6,
    ceiling: 32.1,
    floor: 17.5,
    volatility: 0.46,
    marketValue: 49,
    targetShare: 0,
    opportunityShare: 0
  },
  {
    id: "jalen-hurts",
    name: "Jalen Hurts",
    position: "QB",
    team: "PHI",
    byeWeek: 5,
    projStd: 23.1,
    projPpr: 23.1,
    ros: 22.9,
    ceiling: 30.3,
    floor: 16.8,
    volatility: 0.43,
    marketValue: 46,
    targetShare: 0,
    opportunityShare: 0
  },
  {
    id: "lamar-jackson",
    name: "Lamar Jackson",
    position: "QB",
    team: "BAL",
    byeWeek: 11,
    projStd: 22.6,
    projPpr: 22.6,
    ros: 22.1,
    ceiling: 31.0,
    floor: 15.3,
    volatility: 0.51,
    marketValue: 45,
    targetShare: 0,
    opportunityShare: 0
  },
  {
    id: "patrick-mahomes",
    name: "Patrick Mahomes",
    position: "QB",
    team: "KC",
    byeWeek: 10,
    projStd: 21.8,
    projPpr: 21.8,
    ros: 21.4,
    ceiling: 29.0,
    floor: 15.4,
    volatility: 0.44,
    marketValue: 43,
    targetShare: 0,
    opportunityShare: 0
  },
  {
    id: "joe-burrow",
    name: "Joe Burrow",
    position: "QB",
    team: "CIN",
    byeWeek: 12,
    projStd: 21.1,
    projPpr: 21.1,
    ros: 20.8,
    ceiling: 28.1,
    floor: 14.8,
    volatility: 0.45,
    marketValue: 39,
    targetShare: 0,
    opportunityShare: 0
  },
  {
    id: "cj-stroud",
    name: "C.J. Stroud",
    position: "QB",
    team: "HOU",
    byeWeek: 14,
    projStd: 20.6,
    projPpr: 20.6,
    ros: 20.1,
    ceiling: 27.0,
    floor: 14.2,
    volatility: 0.48,
    marketValue: 37,
    targetShare: 0,
    opportunityShare: 0
  },
  {
    id: "anthony-richardson",
    name: "Anthony Richardson",
    position: "QB",
    team: "IND",
    byeWeek: 14,
    projStd: 20.2,
    projPpr: 20.2,
    ros: 19.4,
    ceiling: 30.4,
    floor: 11.7,
    volatility: 0.62,
    marketValue: 35,
    targetShare: 0,
    opportunityShare: 0
  },
  {
    id: "jordan-love",
    name: "Jordan Love",
    position: "QB",
    team: "GB",
    byeWeek: 6,
    projStd: 19.4,
    projPpr: 19.4,
    ros: 19.2,
    ceiling: 27.4,
    floor: 12.4,
    volatility: 0.56,
    marketValue: 34,
    targetShare: 0,
    opportunityShare: 0
  },
  {
    id: "christian-mccaffrey",
    name: "Christian McCaffrey",
    position: "RB",
    team: "SF",
    byeWeek: 9,
    projStd: 17.8,
    projPpr: 22.4,
    ros: 20.6,
    ceiling: 29.2,
    floor: 12.6,
    volatility: 0.49,
    marketValue: 55,
    targetShare: 0.17,
    opportunityShare: 0.79
  },
  {
    id: "breece-hall",
    name: "Breece Hall",
    position: "RB",
    team: "NYJ",
    byeWeek: 12,
    projStd: 16.1,
    projPpr: 20.5,
    ros: 19.1,
    ceiling: 27.3,
    floor: 11.5,
    volatility: 0.53,
    marketValue: 53,
    targetShare: 0.16,
    opportunityShare: 0.74
  },
  {
    id: "bijan-robinson",
    name: "Bijan Robinson",
    position: "RB",
    team: "ATL",
    byeWeek: 11,
    projStd: 15.8,
    projPpr: 20.0,
    ros: 18.9,
    ceiling: 26.5,
    floor: 11.3,
    volatility: 0.51,
    marketValue: 52,
    targetShare: 0.15,
    opportunityShare: 0.76
  },
  {
    id: "jahmyr-gibbs",
    name: "Jahmyr Gibbs",
    position: "RB",
    team: "DET",
    byeWeek: 5,
    projStd: 15.4,
    projPpr: 19.6,
    ros: 18.2,
    ceiling: 25.6,
    floor: 10.8,
    volatility: 0.52,
    marketValue: 49,
    targetShare: 0.14,
    opportunityShare: 0.68
  },
  {
    id: "jonathan-taylor",
    name: "Jonathan Taylor",
    position: "RB",
    team: "IND",
    byeWeek: 14,
    projStd: 15.2,
    projPpr: 18.1,
    ros: 17.8,
    ceiling: 24.4,
    floor: 10.7,
    volatility: 0.47,
    marketValue: 45,
    targetShare: 0.09,
    opportunityShare: 0.73
  },
  {
    id: "travis-etienne",
    name: "Travis Etienne",
    position: "RB",
    team: "JAX",
    byeWeek: 12,
    projStd: 14.8,
    projPpr: 18.6,
    ros: 17.2,
    ceiling: 24.2,
    floor: 10.2,
    volatility: 0.5,
    marketValue: 43,
    targetShare: 0.12,
    opportunityShare: 0.71
  },
  {
    id: "saquon-barkley",
    name: "Saquon Barkley",
    position: "RB",
    team: "PHI",
    byeWeek: 5,
    projStd: 14.5,
    projPpr: 17.9,
    ros: 16.9,
    ceiling: 23.8,
    floor: 10.1,
    volatility: 0.54,
    marketValue: 41,
    targetShare: 0.11,
    opportunityShare: 0.69
  },
  {
    id: "kyren-williams",
    name: "Kyren Williams",
    position: "RB",
    team: "LAR",
    byeWeek: 6,
    projStd: 14.2,
    projPpr: 17.5,
    ros: 16.8,
    ceiling: 23.0,
    floor: 10.0,
    volatility: 0.55,
    marketValue: 39,
    targetShare: 0.1,
    opportunityShare: 0.67
  },
  {
    id: "devon-achane",
    name: "DeVon Achane",
    position: "RB",
    team: "MIA",
    byeWeek: 6,
    projStd: 13.9,
    projPpr: 17.2,
    ros: 16.4,
    ceiling: 26.4,
    floor: 8.2,
    volatility: 0.68,
    marketValue: 38,
    targetShare: 0.1,
    opportunityShare: 0.59
  },
  {
    id: "kenneth-walker",
    name: "Kenneth Walker",
    position: "RB",
    team: "SEA",
    byeWeek: 8,
    projStd: 13.4,
    projPpr: 16.0,
    ros: 15.8,
    ceiling: 22.1,
    floor: 9.1,
    volatility: 0.57,
    marketValue: 35,
    targetShare: 0.08,
    opportunityShare: 0.65
  },
  {
    id: "james-cook",
    name: "James Cook",
    position: "RB",
    team: "BUF",
    byeWeek: 12,
    projStd: 13.1,
    projPpr: 16.4,
    ros: 15.6,
    ceiling: 21.0,
    floor: 9.4,
    volatility: 0.53,
    marketValue: 33,
    targetShare: 0.11,
    opportunityShare: 0.61
  },
  {
    id: "josh-jacobs",
    name: "Josh Jacobs",
    position: "RB",
    team: "GB",
    byeWeek: 6,
    projStd: 12.9,
    projPpr: 15.2,
    ros: 15.1,
    ceiling: 21.3,
    floor: 8.6,
    volatility: 0.59,
    marketValue: 32,
    targetShare: 0.07,
    opportunityShare: 0.62
  },
  {
    id: "isiah-pacheco",
    name: "Isiah Pacheco",
    position: "RB",
    team: "KC",
    byeWeek: 10,
    projStd: 12.8,
    projPpr: 15.0,
    ros: 14.8,
    ceiling: 20.6,
    floor: 8.8,
    volatility: 0.52,
    marketValue: 30,
    targetShare: 0.07,
    opportunityShare: 0.64
  },
  {
    id: "alvin-kamara",
    name: "Alvin Kamara",
    position: "RB",
    team: "NO",
    byeWeek: 12,
    projStd: 12.0,
    projPpr: 16.8,
    ros: 14.4,
    ceiling: 20.2,
    floor: 8.5,
    volatility: 0.48,
    marketValue: 29,
    targetShare: 0.18,
    opportunityShare: 0.57
  },
  {
    id: "ceedee-lamb",
    name: "CeeDee Lamb",
    position: "WR",
    team: "DAL",
    byeWeek: 7,
    projStd: 14.9,
    projPpr: 21.1,
    ros: 19.8,
    ceiling: 29.8,
    floor: 10.4,
    volatility: 0.5,
    marketValue: 60,
    targetShare: 0.3,
    opportunityShare: 0
  },
  {
    id: "tyreek-hill",
    name: "Tyreek Hill",
    position: "WR",
    team: "MIA",
    byeWeek: 6,
    projStd: 14.6,
    projPpr: 20.4,
    ros: 19.4,
    ceiling: 31.5,
    floor: 9.2,
    volatility: 0.62,
    marketValue: 57,
    targetShare: 0.28,
    opportunityShare: 0
  },
  {
    id: "justin-jefferson",
    name: "Justin Jefferson",
    position: "WR",
    team: "MIN",
    byeWeek: 6,
    projStd: 14.4,
    projPpr: 20.1,
    ros: 19.0,
    ceiling: 29.4,
    floor: 9.8,
    volatility: 0.55,
    marketValue: 58,
    targetShare: 0.29,
    opportunityShare: 0
  },
  {
    id: "jamarr-chase",
    name: "Ja'Marr Chase",
    position: "WR",
    team: "CIN",
    byeWeek: 12,
    projStd: 14.0,
    projPpr: 19.5,
    ros: 18.5,
    ceiling: 28.8,
    floor: 9.4,
    volatility: 0.57,
    marketValue: 56,
    targetShare: 0.28,
    opportunityShare: 0
  },
  {
    id: "amon-ra-st-brown",
    name: "Amon-Ra St. Brown",
    position: "WR",
    team: "DET",
    byeWeek: 5,
    projStd: 13.8,
    projPpr: 19.7,
    ros: 18.6,
    ceiling: 27.0,
    floor: 10.4,
    volatility: 0.42,
    marketValue: 55,
    targetShare: 0.29,
    opportunityShare: 0
  },
  {
    id: "aj-brown",
    name: "A.J. Brown",
    position: "WR",
    team: "PHI",
    byeWeek: 5,
    projStd: 13.6,
    projPpr: 19.0,
    ros: 18.0,
    ceiling: 28.6,
    floor: 8.9,
    volatility: 0.6,
    marketValue: 52,
    targetShare: 0.27,
    opportunityShare: 0
  },
  {
    id: "puka-nacua",
    name: "Puka Nacua",
    position: "WR",
    team: "LAR",
    byeWeek: 6,
    projStd: 13.4,
    projPpr: 18.8,
    ros: 17.7,
    ceiling: 26.8,
    floor: 8.6,
    volatility: 0.55,
    marketValue: 49,
    targetShare: 0.26,
    opportunityShare: 0
  },
  {
    id: "garrett-wilson",
    name: "Garrett Wilson",
    position: "WR",
    team: "NYJ",
    byeWeek: 12,
    projStd: 13.0,
    projPpr: 18.3,
    ros: 17.2,
    ceiling: 26.0,
    floor: 8.3,
    volatility: 0.58,
    marketValue: 47,
    targetShare: 0.27,
    opportunityShare: 0
  },
  {
    id: "marvin-harrison-jr",
    name: "Marvin Harrison Jr.",
    position: "WR",
    team: "ARI",
    byeWeek: 11,
    projStd: 12.8,
    projPpr: 17.8,
    ros: 16.9,
    ceiling: 26.5,
    floor: 7.7,
    volatility: 0.66,
    marketValue: 46,
    targetShare: 0.25,
    opportunityShare: 0
  },
  {
    id: "drake-london",
    name: "Drake London",
    position: "WR",
    team: "ATL",
    byeWeek: 11,
    projStd: 12.6,
    projPpr: 17.4,
    ros: 16.4,
    ceiling: 24.8,
    floor: 8.0,
    volatility: 0.52,
    marketValue: 43,
    targetShare: 0.25,
    opportunityShare: 0
  },
  {
    id: "nico-collins",
    name: "Nico Collins",
    position: "WR",
    team: "HOU",
    byeWeek: 14,
    projStd: 12.4,
    projPpr: 17.1,
    ros: 16.1,
    ceiling: 24.2,
    floor: 7.9,
    volatility: 0.56,
    marketValue: 40,
    targetShare: 0.24,
    opportunityShare: 0
  },
  {
    id: "devonta-smith",
    name: "DeVonta Smith",
    position: "WR",
    team: "PHI",
    byeWeek: 5,
    projStd: 11.8,
    projPpr: 16.3,
    ros: 15.5,
    ceiling: 22.8,
    floor: 7.4,
    volatility: 0.54,
    marketValue: 35,
    targetShare: 0.22,
    opportunityShare: 0
  },
  {
    id: "dk-metcalf",
    name: "DK Metcalf",
    position: "WR",
    team: "SEA",
    byeWeek: 8,
    projStd: 11.6,
    projPpr: 16.0,
    ros: 15.3,
    ceiling: 23.1,
    floor: 6.8,
    volatility: 0.61,
    marketValue: 33,
    targetShare: 0.22,
    opportunityShare: 0
  },
  {
    id: "chris-olave",
    name: "Chris Olave",
    position: "WR",
    team: "NO",
    byeWeek: 12,
    projStd: 11.5,
    projPpr: 15.9,
    ros: 15.2,
    ceiling: 22.5,
    floor: 6.9,
    volatility: 0.58,
    marketValue: 34,
    targetShare: 0.23,
    opportunityShare: 0
  },
  {
    id: "dj-moore",
    name: "DJ Moore",
    position: "WR",
    team: "CHI",
    byeWeek: 7,
    projStd: 11.1,
    projPpr: 15.0,
    ros: 14.5,
    ceiling: 21.8,
    floor: 6.6,
    volatility: 0.59,
    marketValue: 30,
    targetShare: 0.21,
    opportunityShare: 0
  },
  {
    id: "deebo-samuel",
    name: "Deebo Samuel",
    position: "WR",
    team: "SF",
    byeWeek: 9,
    projStd: 10.8,
    projPpr: 14.7,
    ros: 14.1,
    ceiling: 23.6,
    floor: 5.9,
    volatility: 0.67,
    marketValue: 29,
    targetShare: 0.2,
    opportunityShare: 0
  },
  {
    id: "travis-kelce",
    name: "Travis Kelce",
    position: "TE",
    team: "KC",
    byeWeek: 10,
    projStd: 10.5,
    projPpr: 15.8,
    ros: 14.8,
    ceiling: 23.0,
    floor: 6.5,
    volatility: 0.54,
    marketValue: 38,
    targetShare: 0.24,
    opportunityShare: 0
  },
  {
    id: "sam-laporta",
    name: "Sam LaPorta",
    position: "TE",
    team: "DET",
    byeWeek: 5,
    projStd: 9.9,
    projPpr: 15.1,
    ros: 14.1,
    ceiling: 21.5,
    floor: 6.0,
    volatility: 0.51,
    marketValue: 36,
    targetShare: 0.23,
    opportunityShare: 0
  },
  {
    id: "mark-andrews",
    name: "Mark Andrews",
    position: "TE",
    team: "BAL",
    byeWeek: 11,
    projStd: 9.6,
    projPpr: 14.3,
    ros: 13.4,
    ceiling: 20.4,
    floor: 5.9,
    volatility: 0.53,
    marketValue: 33,
    targetShare: 0.22,
    opportunityShare: 0
  },
  {
    id: "trey-mcbride",
    name: "Trey McBride",
    position: "TE",
    team: "ARI",
    byeWeek: 11,
    projStd: 9.3,
    projPpr: 14.5,
    ros: 13.5,
    ceiling: 20.0,
    floor: 5.7,
    volatility: 0.49,
    marketValue: 34,
    targetShare: 0.25,
    opportunityShare: 0
  },
  {
    id: "george-kittle",
    name: "George Kittle",
    position: "TE",
    team: "SF",
    byeWeek: 9,
    projStd: 8.9,
    projPpr: 13.5,
    ros: 12.9,
    ceiling: 22.4,
    floor: 4.8,
    volatility: 0.69,
    marketValue: 28,
    targetShare: 0.2,
    opportunityShare: 0
  },
  {
    id: "tj-hockenson",
    name: "T.J. Hockenson",
    position: "TE",
    team: "MIN",
    byeWeek: 6,
    projStd: 8.2,
    projPpr: 12.8,
    ros: 12.0,
    ceiling: 18.2,
    floor: 5.0,
    volatility: 0.52,
    marketValue: 24,
    targetShare: 0.21,
    opportunityShare: 0
  },
  {
    id: "evan-engram",
    name: "Evan Engram",
    position: "TE",
    team: "JAX",
    byeWeek: 12,
    projStd: 7.8,
    projPpr: 12.4,
    ros: 11.7,
    ceiling: 17.1,
    floor: 4.6,
    volatility: 0.47,
    marketValue: 22,
    targetShare: 0.22,
    opportunityShare: 0
  },
  {
    id: "kyle-pitts",
    name: "Kyle Pitts",
    position: "TE",
    team: "ATL",
    byeWeek: 11,
    projStd: 7.6,
    projPpr: 11.6,
    ros: 11.2,
    ceiling: 17.4,
    floor: 4.2,
    volatility: 0.63,
    marketValue: 21,
    targetShare: 0.19,
    opportunityShare: 0
  }
];

export const PLAYER_MAP = Object.fromEntries(PLAYERS.map((p) => [p.id, p]));

export const SAMPLE_LEAGUES = [
  {
    id: "sleeper_beta_101",
    name: "Dynasty Lab League",
    scoring: "ppr",
    roster: [
      "jalen-hurts",
      "jordan-love",
      "breece-hall",
      "travis-etienne",
      "james-cook",
      "josh-jacobs",
      "ceedee-lamb",
      "drake-london",
      "devonta-smith",
      "dk-metcalf",
      "kyle-pitts",
      "trey-mcbride",
      "dj-moore",
      "isiah-pacheco"
    ],
    record: "7-4"
  },
  {
    id: "sleeper_beta_202",
    name: "Commissioner Slackers",
    scoring: "half",
    roster: [
      "patrick-mahomes",
      "anthony-richardson",
      "bijan-robinson",
      "jahmyr-gibbs",
      "kenneth-walker",
      "alvin-kamara",
      "aj-brown",
      "puka-nacua",
      "chris-olave",
      "deebo-samuel",
      "travis-kelce",
      "sam-laporta",
      "nico-collins",
      "marvin-harrison-jr"
    ],
    record: "5-6"
  }
];

export const STARTER_FORMAT = {
  QB: 1,
  RB: 2,
  WR: 2,
  TE: 1,
  FLEX: 1
};
